Replace saiUI with bslib
Riksrevisjonen/pioneeR pull request #10
Opened 2023-01-09 11:53 UTC by Aeilert

Hi @ohjakobsen,

Here is an initial attempt at solving #2. Please note the following: 

* The functionality to hide the "Analysis" and "Malmquist" tabs on application start up doesn't work, even with the discussed workaround in `pioneer.js`. Any suggestion you have on this is welcome. 
* There are some minor changes in the layout, including the file-input box and colouring. We might want to tweak this. 
* Great if you could go over the overall functionality as you are more familiar with the app, and there might be something that I have missed. 
* As a simple solution `dropdown_button()` in utils.R is just a copy-paste from `saiUI::bs4dropdown()`. Let me know if you think we should do this differently. 

Feel free to implement any changes directly if you prefer.

2023-01-16 14:52 UTC, ohjakobsen commented
The app fails because of dependency on the function `singleLayout()` from saiUI. `singleLayout()` can be replaced with:
```r
tags$div(class = 'container mt-1', tags$div(class = 'row', tags$div(class = 'col-12', ...)))
```
Also note that the function `card()` was added to bslib 0.4.2. This should be reflected in `DESCRIPTION`.

2023-01-17 10:02 UTC, Aeilert commented
> The app fails because of dependency on the function `singleLayout()` from saiUI. `singleLayout()` can be replaced with:
> 
> ```r
> tags$div(class = 'container mt-1', tags$div(class = 'row', tags$div(class = 'col-12', ...)))
> ```
> 
> Also note that the function `card()` was added to bslib 0.4.2. This should be reflected in `DESCRIPTION`.

This should now be fixed.

2023-03-10 13:40 UTC, ohjakobsen commented
I've added a fix for the JS issue to support hiding/showing tabs depending on the type of analysis selected. There is still a bug in the Malmquist tab that needs to be solved. I'm going to keep the review open until I've found a fix.

2023-03-10 14:42 UTC, ohjakobsen requested changes
Move `utils.R` to proper location. I've added several commits to fix bugs with this PR. All changes should be verified.

2023-03-10 14:42 UTC, ohjakobsen commented on inst/app/global.R
> +source('utils.R')
Move `utils.R` to R directory inside `./inst/app/`. Files inside this structure is automatically sourced with shiny 1.5.0 and above

2023-03-10 15:19 UTC, Aeilert commented
@ohjakobsen: I moved the utils.R file inside inst/app/R and have verified that the  functionality to hide the "Analysis" and "Malmquist" tabs on start-up works, as well as swapping between them based on other user selections.

2023-03-10 20:56 UTC, ohjakobsen approved these changes

2023-03-13 12:12 UTC, merged