26 compare models
Riksrevisjonen/pioneeR pull request #29
Opened 2023-06-20 13:07 UTC by ohjakobsen

The PR adds the ability to save models so that they can be compared. When two or more models are saved, the user can navigate to a new "Compare" tab. A table of all efficiency scores from the different models are shown. This PR also add the ability to manage models and delete models that are not needed in the comparison view.

2023-06-21 10:43 UTC, Aeilert requested changes
This is a very good addition to the current functionality. A couple of feedbacks: 

* On my machine the Compare tab shows severe latency when saving more then 4-5 models. There is a somewhat lag for the 5th model, and then increasing latency and memory issues after that. I think a max limit of five models would be good. 
* The Compare tab should pop-up after the first saved model, not the second. It makes sense that you need two models to have something to compare, but it is not intuitive that this functionality exists unless you know about it. The need to save two models can thus be confusing to the user. 
* This is only available for non-timeseries data. I think that's okay, but we should create an issue for similar functionality to be added to the Malmquist tab.

2023-06-21 13:55 UTC, ohjakobsen commented
@Aeilert: I've added a maximum of 6 models (my machine coped with fine with a large number, so it might be the size of your data that is the issue). I've also tweaked the UI an added a download option.

2023-06-21 14:06 UTC, Aeilert approved these changes

2023-06-22 09:25 UTC, ohjakobsen commented
@Aeilert: see new commits to this PR. If you have time, please confirm that the bug has been fixed. I've bumped the number of models to 10, as the bug was causing the performance issues. Please also note that I have changes the requirements for R and Shiny to 4.1 and 1.7 respectively.

2023-06-22 10:01 UTC, merged