Fixes for release 0623
Riksrevisjonen/pioneeR pull request #33
Opened 2023-06-26 07:49 UTC by ohjakobsen

This PR closes #25 and #30 and introduce various other fixes:

* List wise deletion is performed if the user selects input and/or output variables where there are incomplete cases
* For VRS, the frontier line could dip if one or more observations on the far right side on the x-axis has a value lower than the maximum value on the y-axis. This problem has been resolved, and frontier line for NIRS has been added as well
* General UI improvements
* Bumped version to 0.1.0

2023-06-26 16:02 UTC, lse81 commented on inst/app/conditionalUI.R
Looks ok.

2023-06-26 16:12 UTC, lse81 commented on inst/app/server.R
There is some problems with the listwise deletion function.  Listwise deletion was not performed  even though I had some missing observation in my dataset.

2023-06-26 16:17 UTC, lse81 commented on inst/app/server.R
The slack-values were all 0 when using an output-oriented model. It should be slack values differenct from 0 for both input and output-oriented models.

2023-06-26 16:22 UTC, lse81 requested changes
This looks very good. I like the listwise deletion function. However i still get some errors we have to look into. 
1) Error message  "could not find function "card"" still present when open the app from R-studio. 
2) Listwise deletion was not performed neither with .csv-file nor the .dta-file. 
3) There are some problems with the encoding. With UTF8 we do not get Æ, Ø, Å.  
4) I get an error message when specifying the model with either single input/output or multiple inputs/outputs. "Error: Y is not a numeric matrix (or numeric data.frame)"
'Y' is not a numeric matrix (or numeric data.fram

2023-06-27 04:44 UTC, ohjakobsen commented
> This looks very good. I like the listwise deletion function. However i still get some errors we have to look into.
> 
> 1. Error message  "could not find function "card"" still present when open the app from R-studio.
> 2. Listwise deletion was not performed neither with .csv-file nor the .dta-file.
> 3. There are some problems with the encoding. With UTF8 we do not get Æ, Ø, Å.
> 4. I get an error message when specifying the model with either single input/output or multiple inputs/outputs. "Error: Y is not a numeric matrix (or numeric data.frame)"
>    'Y' is not a numeric matrix (or numeric data.fram

Issue 1 and 2 is probably an issue with your local install. Encoding should be supported, but this might be a Windows issue that we need to look into. The last error message is a bit more cryptic and needs to be explored. I will need a step by step guide to reproduce the issue.

2023-06-27 12:46 UTC, ohjakobsen commented on inst/app/server.R
This was an issue with the commit history. Should be fixed on the latest commit.

2023-06-27 12:47 UTC, ohjakobsen commented on inst/app/server.R
We need to look at this in a separate PR. We can probably do this in relation to #30.

2023-06-27 12:48 UTC, lse81 approved these changes
Looks good!

2023-06-27 12:48 UTC, merged